const fs=require('node:fs'),assert=require('node:assert/strict');const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://classroom.test/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:'<html><style>body{margin:0;background:#122a48}#player{width:1040px;height:700px;position:relative}#player:fullscreen{width:100vw;height:100vh}video{width:100%;height:100%}.vjs-control-bar{height:30px;background:#eee}#pane-voice{color:white}</style><div id="player"><video src="https://vod.cmc.zju.edu.cn/mock.mp4"></video><div class="vjs-control-bar"><button class="vjs-fullscreen-control" title="全屏">网站全屏</button></div></div><div id="pane-voice"><div class="trans-item"><div class="item-title">00:00:10</div><div class="trans-lan"><div>We discuss the register and the instruction pipeline.</div></div></div><div class="trans-item"><div class="item-title">00:00:20</div><div class="trans-lan"><div>Next, the processor decodes the instruction.</div></div></div></div><div id="pane-ppt"><div class="tab-ppt"><img src="https://images.test/one.svg"><span class="time">00:00:00</span></div><div class="tab-ppt"><img src="https://images.test/two.svg"><span class="time">00:00:20</span></div></div></html>'}));
 await page.route('https://vod.cmc.zju.edu.cn/**',r=>r.abort());await page.route('https://images.test/**',r=>r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="650"><rect width="100%" height="100%" fill="#f9fbff"/><text x="60" y="80" fill="#174d8c" font-size="32">COMPUTER ARCHITECTURE / 01</text><text x="60" y="160" fill="#233954" font-size="50">Instruction Pipeline</text><rect x="60" y="240" width="260" height="160" rx="20" fill="#dfeaff"/><text x="95" y="335" font-size="36">Fetch</text><rect x="375" y="240" width="260" height="160" rx="20" fill="#fff1b7"/><text x="407" y="335" font-size="36">Decode</text><rect x="690" y="240" width="250" height="160" rx="20" fill="#dcefdc"/><text x="720" y="335" font-size="36">Execute</text></svg>'}));
 await page.goto('https://classroom.test/#/replay?course_id=keyboard&sub_id=1');
 await page.evaluate(()=>{
 window.saved={};window.GM_getValue=(k,d)=>saved[k]??d;window.GM_setValue=(k,v)=>saved[k]=v;window.GM_deleteValue=k=>delete saved[k];window.GM_registerMenuCommand=()=>{};
 window.aiRequests=[];window.GM_xmlhttpRequest=o=>{if(o.method==='POST'){aiRequests.push(JSON.parse(o.data));const timer=setTimeout(()=>o.onload({status:200,responseText:JSON.stringify({output:[{type:'message',content:[{type:'output_text',text:'寄存器就像处理器手边的小便签，用来暂存正在处理的数据。指令依次经过取指、译码和执行。'}]}]})}),10);return{abort(){clearTimeout(timer);o.onabort?.();}};}const timer=setTimeout(()=>o.onload({status:206,responseHeaders:'Content-Range: bytes 0-15/16',response:new Blob([new Uint8Array([0,0,0,16,102,116,121,112,105,115,111,109,0,0,0,0])],{type:'video/mp4'})}),10);return{abort(){clearTimeout(timer);o.onabort?.();}};};
 const v=document.querySelector('video');window.t=12;window.paused=true;window.plays=0;Object.defineProperties(v,{currentTime:{get:()=>t,set:n=>t=n},duration:{get:()=>3600},paused:{get:()=>paused},readyState:{get:()=>1},currentSrc:{get:()=>v.src}});v.load=()=>setTimeout(()=>v.dispatchEvent(new Event('loadedmetadata')),0);v.play=()=>{paused=false;plays++;return Promise.resolve();};v.pause=()=>{paused=true;};v.addEventListener('error',e=>e.stopImmediatePropagation(),true);
 });
 await page.addScriptTag({path:'zhiyun-subtitles.user.js'});const ui=page.locator('#zy-subtitle-host');await page.waitForTimeout(700);
 await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>paused),false);assert.equal(await page.evaluate(()=>plays),1);
 await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>t),22);await page.keyboard.press('ArrowLeft');assert.equal(await page.evaluate(()=>t),12);
 await ui.locator('#collapse').click();await ui.locator('#compact').click();await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>paused),true);await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>t),22);
 await ui.locator('#settings-open').click();await ui.locator('#settings-tab-translation').click();await ui.locator('#translation-domain').fill('Register = CPU storage');const before=await page.evaluate(()=>t);await page.keyboard.press('ArrowLeft');await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>t),before);assert.equal(await page.evaluate(()=>paused),true);
 await ui.locator('#settings-content').evaluate(e=>{e.scrollTop=0;});await page.screenshot({path:'settings-preview.png'});await page.keyboard.press('Escape');assert.ok(await ui.locator('#settings-dialog').isHidden());
 await ui.locator('#settings-open').click();await ui.locator('#settings-tab-storage').click();await ui.locator('#cache-progressive').uncheck();await ui.locator('#settings-close').click();await ui.locator('#study-cache > summary').click();await ui.locator('#cache-details > summary').click();await ui.locator('#cache-download').click();await page.waitForTimeout(300);
 assert.ok(await page.locator('#player > video').evaluate(v=>v.controls));assert.ok(await ui.locator('#cache-transport').isHidden());assert.equal(await page.locator('.vjs-control-bar').evaluate(e=>getComputedStyle(e).display),'none');
 await ui.locator('#cache-source').click();await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>paused),false);await page.keyboard.press('ArrowLeft');assert.equal(await page.evaluate(()=>t),12);
 await ui.locator('#cache-online').click();await page.waitForTimeout(180);assert.equal(await page.locator('#player > video').evaluate(v=>v.controls),false);assert.notEqual(await page.locator('.vjs-control-bar').evaluate(e=>getComputedStyle(e).display),'none');
 await ui.locator('summary').filter({hasText:'视频缓存'}).click();await ui.locator('#show-slides').click();await page.waitForTimeout(120);
 await page.locator('.vjs-fullscreen-control').click();await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>document.fullscreenElement.id),'player');assert.ok(await page.evaluate(()=>document.fullscreenElement.contains(document.getElementById('zy-subtitle-host'))));assert.ok(await ui.locator('#slides').isVisible());assert.ok(await ui.locator('#caption').isVisible());
 await ui.locator('#transcript-open').click();await page.waitForTimeout(150);assert.ok(await ui.locator('#transcript').isVisible());assert.equal(await ui.locator('.transcript-cue').count(),2);await ui.locator('.transcript-cue').last().click();assert.equal(await page.evaluate(()=>t),20);await page.waitForTimeout(150);assert.equal(await ui.locator('#slide-page').textContent(),'2 / 2');
 await ui.locator('#transcript-close').focus();await page.keyboard.press('Space');assert.ok(await ui.locator('#transcript').isHidden());await ui.locator('#compact').click();await page.screenshot({path:'learning-preview.png'});
 await ui.locator('#focus-fullscreen').click();await page.evaluate(()=>document.querySelector('video').requestFullscreen());await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>document.fullscreenElement.id),'player');await page.evaluate(()=>document.exitFullscreen());
 // The primary action should open the current PPT from the default closed state.
 await ui.locator('#slide-close').evaluate(e=>e.click());assert.ok(await ui.locator('#slides').isHidden());
 await page.route('https://classroom.test/slide.svg',r=>r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="900" height="600"><rect width="100%" height="100%" fill="#fff8dd"/><text x="60" y="100" font-size="40">Instruction Pipeline</text></svg>'}));
 await page.evaluate(()=>document.querySelectorAll('#pane-ppt img').forEach(img=>img.src='https://classroom.test/slide.svg'));
 // The installed bundle must wire AI credentials, slide image, settings and course context.
 await page.evaluate(()=>{saved['ark-api-key']='mock-key';const canvas=document.createElement('canvas');canvas.width=900;canvas.height=600;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff8dd';ctx.fillRect(0,0,900,600);ctx.fillStyle='#214f81';ctx.font='40px sans-serif';ctx.fillText('Instruction Pipeline',60,100);document.querySelector('#zy-subtitle-host').shadowRoot.getElementById('slide-image').src=canvas.toDataURL('image/png');});
 await ui.locator('#ai-open').click();await page.waitForFunction(()=>aiRequests.length===1);assert.ok(await ui.locator('#slides').isVisible());await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>aiRequests[0].input.at(-1).content.filter(c=>c.type==='input_image').length),1,'primary explain action sends current PPT');await ui.locator('#ai-question').fill('为什么需要寄存器？');await ui.locator('#ai-send').click();await page.waitForFunction(()=>aiRequests.length===2);await page.waitForTimeout(100);
 assert.match(await ui.locator('#ai-log').textContent(),/小便签/);assert.match(await page.evaluate(()=>aiRequests[1].input.at(-1).content[0].text),/processor/);
 await ui.locator('#ai-slide-action').click();await page.waitForFunction(()=>aiRequests.length===3);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>aiRequests[2].input.at(-1).content.filter(c=>c.type==='input_image').length),1);
 await page.screenshot({path:'ai-integrated-preview.png'});
 await ui.locator('#ai-settings-open').click();assert.ok(await ui.locator('#settings-ai').isVisible());await ui.locator('#settings-close').click();
 assert.deepEqual(errors,[]);console.log('PASS: integrated AI text/PPT/settings/context; global space/arrows with button focus, editing exemption, one native local control bar, online restore, website/video fullscreen redirection, visible PPT/caption/transcript and subtitle seek.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
